import * as z from "zod/mini";

/**
 * The longest name a key may carry. A name is a label a person reads in a list of their keys ("CI deploys", "laptop script"), so this is long enough for a descriptive phrase and short enough that a list of keys stays readable.
 */
export const API_KEY_NAME_MAX_LENGTH = 64;

/**
 * A key's name: at least one character, at most {@link API_KEY_NAME_MAX_LENGTH}, with no leading or trailing whitespace. Names are unique per owner, so whitespace that is invisible in a list would otherwise let two keys look identical while being distinct.
 */
export const apiKeyNameSchema = z.string().check(
  z.minLength(1),
  z.maxLength(API_KEY_NAME_MAX_LENGTH),
  z.refine((name) => name.trim() === name, {
    message: "A key name must not start or end with whitespace",
  }),
);

const ownerIdSchema = z.string().check(z.minLength(1));

/** A key owned by a person: the id of a row in better-auth's `user` table. Deleting the person deletes their keys. */
export const apiKeyUserOwnerSchema = z.object({
  kind: z.literal("user"),
  id: ownerIdSchema,
});

/**
 * A key owned by a system principal: a named, non-human caller the host owns and stores itself, such as a deployment pipeline or an integration. The package records only the principal's id; what the principal may do, and whether it still exists, is the host's to decide on every request. Nothing references a principal, so removing a person never touches its keys, and removing the principal is the host's call to the service's `revokeAllForOwner`.
 */
export const apiKeySystemOwnerSchema = z.object({
  kind: z.literal("system"),
  id: ownerIdSchema,
});

/**
 * Whom a key belongs to and acts as: a person or a system principal, told apart by `kind`, which every caller must name. A user's id and a principal's id live in separate namespaces, so the same id string names two different owners when the kinds differ, and an owner without a kind is refused rather than guessed at, so a principal's id can never be taken for a person's. Identity enters the package as data: the host resolves who is asking, and the package only records and compares the owner.
 */
export const apiKeyOwnerSchema = z.discriminatedUnion("kind", [
  apiKeyUserOwnerSchema,
  apiKeySystemOwnerSchema,
]);
export type ApiKeyOwner = z.output<typeof apiKeyOwnerSchema>;
export type ApiKeyUserOwner = z.output<typeof apiKeyUserOwnerSchema>;
export type ApiKeySystemOwner = z.output<typeof apiKeySystemOwnerSchema>;

/**
 * A key as a store holds it. Scopes and claims are opaque JSON at this layer: the store neither knows nor checks their shape, and the service validates them against the host's schemas whenever it reads a key back, so a store can never hand the host data typed as scopes that was never checked. The presented key itself is never stored, only its keyed hash.
 */
export const storedApiKeySchema = z.object({
  /** Generated by the service, not by the store, so every store names a key the same way. */
  id: z.string().check(z.minLength(1)),
  owner: apiKeyOwnerSchema,
  name: apiKeyNameSchema,
  /** The keyed hash of the presented key ({@link KeyHasher}), the only form of the key that is ever stored. Unique across every owner. */
  keyHash: z.string().check(z.minLength(1)),
  /** The key's prefix and first few characters, shown in lists so a person can tell their keys apart without the key being recoverable from it. */
  start: z.string().check(z.minLength(1)),
  scopes: z.unknown(),
  claims: z.unknown(),
  createdAt: z.date(),
  /** When the key stops authenticating, or `null` for a system principal's key the host chose to create with no expiry. Explicitly `null`, never absent, so a store that drops the field fails validation rather than silently granting a key that never expires. */
  expiresAt: z.nullable(z.date()),
  /** Who created the key, as the host names them: plain text with no reference to any table, so removing the creator changes nothing about the key. Absent when the host did not say. */
  createdBy: z.optional(z.string().check(z.minLength(1))),
  /** When the key last authenticated a request, to within the service's last-used interval; absent until its first use. */
  lastUsedAt: z.optional(z.date()),
});
export type StoredApiKey = z.output<typeof storedApiKeySchema>;

/**
 * What a person sees of a key: everything but its hash, scopes and claims. `ownerId` repeats `owner.id`, so code written before system principals existed reads unchanged; a host that creates system keys must branch on `owner.kind` before treating `ownerId` as a person's id.
 */
export type ApiKeySummary = Omit<
  StoredApiKey,
  "keyHash" | "scopes" | "claims"
> & {
  readonly ownerId: string;
};

/** A key whose scopes and claims have passed the host's schemas, typed by them. */
export type ApiKey<Scopes, Claims> = ApiKeySummary & {
  readonly scopes: Scopes;
  readonly claims: Claims;
};
