import * as z from "zod/mini";

/**
 * The longest name a key may carry. A name is a label a person reads in a list of their keys ("CI deploys", "laptop script"), so this is long enough for a descriptive phrase and short enough that a list of keys stays readable.
 */
export const API_KEY_NAME_MAX_LENGTH = 64;

/**
 * A key's name: at least one character, at most {@link API_KEY_NAME_MAX_LENGTH}, with no leading or trailing whitespace. Names are unique per owner, so whitespace that is invisible in a list would otherwise let two keys look identical while being distinct.
 */
export const apiKeyNameSchema = z.string().check(
  z.minLength(1),
  z.maxLength(API_KEY_NAME_MAX_LENGTH),
  z.refine((name) => name.trim() === name, {
    message: "A key name must not start or end with whitespace",
  }),
);

/**
 * Whom a key belongs to and acts as. Identity enters the package as data: the host resolves who is asking, and the package only records and compares the id.
 */
export const apiKeyOwnerSchema = z.object({
  id: z.string().check(z.minLength(1)),
});
export type ApiKeyOwner = z.output<typeof apiKeyOwnerSchema>;

/**
 * A key as a store holds it. Scopes and claims are opaque JSON at this layer: the store neither knows nor checks their shape, and the service validates them against the host's schemas whenever it reads a key back, so a store can never hand the host data typed as scopes that was never checked. The presented key itself is never stored, only its keyed hash.
 */
export const storedApiKeySchema = z.object({
  /** Generated by the service, not by the store, so every store names a key the same way. */
  id: z.string().check(z.minLength(1)),
  ownerId: z.string().check(z.minLength(1)),
  name: apiKeyNameSchema,
  /** The keyed hash of the presented key ({@link KeyHasher}), the only form of the key that is ever stored. Unique across every owner. */
  keyHash: z.string().check(z.minLength(1)),
  /** The key's prefix and first few characters, shown in lists so a person can tell their keys apart without the key being recoverable from it. */
  start: z.string().check(z.minLength(1)),
  scopes: z.unknown(),
  claims: z.unknown(),
  createdAt: z.date(),
  expiresAt: z.date(),
  /** When the key last authenticated a request, to within the service's last-used interval; absent until its first use. */
  lastUsedAt: z.optional(z.date()),
});
export type StoredApiKey = z.output<typeof storedApiKeySchema>;

/** What a person sees of a key: everything but its hash, scopes and claims. */
export type ApiKeySummary = Omit<StoredApiKey, "keyHash" | "scopes" | "claims">;

/** A key whose scopes and claims have passed the host's schemas, typed by them. */
export type ApiKey<Scopes, Claims> = ApiKeySummary & {
  readonly scopes: Scopes;
  readonly claims: Claims;
};
